// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutMediaOverlay from '@/components/sections/about/AboutMediaOverlay';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutMediaOverlay
          tag="About Us"
          title="Expertise You Can Trust"
          description="Team Work Projects is dedicated to providing high-quality trade services in Cape Town. We blend professional reliability with the convenience of a 24/7 service model to ensure your home or business runs smoothly at all times."
          imageSrc="http://img.b2bpic.net/free-photo/cardboard-house-with-tools-top-view_23-2148393088.jpg"
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
