// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Contact Us"
          text="Ready to get started on your next home improvement or electrical project? Reach out for a free, no-obligation quote today."
          primaryButton={{
            text: "Request a Free Quote",
            href: "#",
          }}
          secondaryButton={{
            text: "Call Now: 061 096 7678",
            href: "tel:0610967678",
          }}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
