// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTabbedAccordion from '@/components/sections/faq/FaqTabbedAccordion';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTabbedAccordion
          tag="Support"
          title="Common Questions"
          description="Find answers to help you get started with our services."
          categories={[
            {
              name: "General",
              items: [
                {
                  question: "What areas do you cover?",
                  answer: "We serve all areas across Cape Town.",
                },
                {
                  question: "Are you open on weekends?",
                  answer: "Yes, we provide 24/7 service all year round.",
                },
                {
                  question: "How do I get a quote?",
                  answer: "Request a free quote through our contact form.",
                },
              ],
            },
            {
              name: "Electrical",
              items: [
                {
                  question: "Do you provide COC certificates?",
                  answer: "Yes, we are fully licensed for electrical compliance.",
                },
                {
                  question: "Do you handle emergency electrical issues?",
                  answer: "We offer 24-hour rapid response for emergencies.",
                },
              ],
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
