// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTabbedAccordion from '@/components/sections/faq/FaqTabbedAccordion';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTabbedAccordion
        tag="FAQ"
        title="Frequently Asked Questions"
        description="Find answers to common questions about our services, pricing, and availability."
        categories={[{"items":[{"question":"Are you available for electrical emergencies 24/7?","answer":"Yes, we offer 24/7 emergency electrical services across Cape Town. Call us anytime on 061 096 7678 for immediate assistance."},{"answer":"Yes, we provide free, no-obligation estimates for all our services including electrical work, painting, tiling, and tree felling.","question":"Do you provide free estimates?"},{"answer":"We service the greater Cape Town area, including the CBD, Southern Suburbs, Northern Suburbs, Atlantic Seaboard, and surrounding areas.","question":"What areas in Cape Town do you service?"},{"answer":"Yes, we have the expertise and capacity to handle both small residential repairs and large-scale commercial installations and maintenance contracts.","question":"Do you handle both residential and commercial projects?"}],"name":"General"},{"name":"Electrical","items":[{"question":"Are your electricians certified?","answer":"Absolutely. Our electricians are fully qualified and registered to issue Electrical Compliance Certificates (CoC) for your property."}]}]}
        textAnimation="slide-up"
      />
        </SectionErrorBoundary>
      </div>
  );
}
