// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroSplitVerticalMarquee from '@/components/sections/hero/HeroSplitVerticalMarquee';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroSplitVerticalMarquee
          tag="Available 24/7"
          title="Trusted Trades Available 24/7 Cape Towns Choice"
          description="From electrical installations and compliance certificates to painting, tiling, and tree felling—Team Work Projects delivers premium workmanship when you need it Available around the clock, every day"
          primaryButton={{
            text: "Request a Free Quote",
            href: "#contact",
          }}
          secondaryButton={{
            text: "Call Now: 061 096 7678",
            href: "tel:0610967678",
          }}
          leftItems={[
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3G8pr39VQA8qyoH5BQldYgFWqm6/uploaded-1783497508992-jc7ko550.jpg?_wi=1",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3G8pr39VQA8qyoH5BQldYgFWqm6/uploaded-1783497508993-7j91lxbl.jpg?_wi=1",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3G8pr39VQA8qyoH5BQldYgFWqm6/uploaded-1783497508994-0eccbbf2.jpg?_wi=1",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3G8pr39VQA8qyoH5BQldYgFWqm6/uploaded-1783497508994-0bmy1vkw.jpg?_wi=1",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3G8pr39VQA8qyoH5BQldYgFWqm6/uploaded-1783497508995-mdlqp5t6.jpg?_wi=1",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/african-american-steel-worker-analyzing-finished-products-while-working-factory_637285-4742.jpg",
            },
          ]}
          rightItems={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/service-maintenance-worker-repairing_23-2149176718.jpg",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3G8pr39VQA8qyoH5BQldYgFWqm6/uploaded-1783497508995-mdlqp5t6.jpg?_wi=2",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3G8pr39VQA8qyoH5BQldYgFWqm6/uploaded-1783497508994-0bmy1vkw.jpg?_wi=2",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3G8pr39VQA8qyoH5BQldYgFWqm6/uploaded-1783497508994-0eccbbf2.jpg?_wi=2",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3G8pr39VQA8qyoH5BQldYgFWqm6/uploaded-1783497508993-7j91lxbl.jpg?_wi=2",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3G8pr39VQA8qyoH5BQldYgFWqm6/uploaded-1783497508992-jc7ko550.jpg?_wi=2",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
