// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsFeatureCards from '@/components/sections/metrics/MetricsFeatureCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsFeatureCards
          tag="Our Impact"
          title="Professional Standards"
          description="We stand by our work with clear commitments to quality and responsiveness."
          metrics={[
            {
              value: "24/7",
              title: "Always On",
              features: [
                "Anytime emergency support",
                "Ready to deploy",
                "Fast response times",
              ],
            },
            {
              value: "100%",
              title: "Workmanship",
              features: [
                "Qualified technicians",
                "Quality-assured results",
                "Compliance certified",
              ],
            },
            {
              value: "Cape Town",
              title: "Local Service",
              features: [
                "Deep local knowledge",
                "Fast arrival",
                "Community focused",
              ],
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
