// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "projects" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ProjectsSection(): React.JSX.Element {
  return (
    <div id="projects" data-section="projects">
        <SectionErrorBoundary name="projects">
              <FeaturesRevealCardsBento
          tag="Recent Work"
          title="Portfolio Highlights"
          description="A glimpse into our recent craftsmanship and professional successes across Cape Town."
          items={[
            {
              title: "Electrical Refurb",
              description: "Panel board replacement and full certification.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/male-electrician-electrical-technician-working-switchboard_169016-65750.jpg",
            },
            {
              title: "Interior Painting",
              description: "High-end finish for a modern luxury home.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/full-shot-people-painting-walls_23-2149344041.jpg",
            },
            {
              title: "Kitchen Tiling",
              description: "Modern patterned tiles installed with precision.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/tiler-working-renovation-apartment_23-2149278591.jpg",
            },
            {
              title: "Garden Clearing",
              description: "Safe tree felling in a confined residential space.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/trowels-near-fence_23-2147714873.jpg",
            },
            {
              title: "Ceiling Install",
              description: "Custom ceiling panels for a garage workshop.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/installing-ceramic-floor-tiles-construction-site-construction-workers-workers-laying-tiles-floor-with-cement-adhesive-renovating-floor_166373-2132.jpg",
            },
            {
              title: "Outdoor Tiling",
              description: "Durable finishes for a modern pool area.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/focus-wood-shaper-used-by-carpenter-smoothing-out-panels_482257-89312.jpg",
            },
            {
              title: "Emergency Electrical",
              description: "Rapid response troubleshooting for a local business.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/african-american-employee-talking-landline-phone_482257-96280.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
