// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "projects" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ProjectsSection(): React.JSX.Element {
  return (
    <div id="projects" data-section="projects">
        <SectionErrorBoundary name="projects">
              <FeaturesRevealCardsBento
          tag="Recent Work"
          title="Portfolio Highlights"
          description="A glimpse into our recent craftsmanship and professional successes across Cape Town."
          items={[
            {
              title: "Electrical Refurb",
              description: "Panel board replacement and full certification.",
              href: "#",
              imageSrc: "https://images.unsplash.com/photo-1581141849291-1125c7b692b5?q=80&w=800&auto=format&fit=crop",
            },
            {
              title: "Interior Painting",
              description: "High-end finish for a modern luxury home.",
              href: "#",
              imageSrc: "https://images.unsplash.com/photo-1508873881324-c92a3fc536ba?q=80&w=800&auto=format&fit=crop",
            },
            {
              title: "Kitchen Tiling",
              description: "Modern patterned tiles installed with precision.",
              href: "#",
              imageSrc: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=800&auto=format&fit=crop",
            },
            {
              title: "Garden Clearing",
              description: "Safe tree felling in a confined residential space.",
              href: "#",
              imageSrc: "https://images.unsplash.com/photo-1590486803833-1c5dc8ddd4c8?q=80&w=800&auto=format&fit=crop",
            },
            {
              title: "Ceiling Install",
              description: "Custom ceiling panels for a garage workshop.",
              href: "#",
              imageSrc: "https://images.unsplash.com/photo-1541888086925-920a0e414e51?q=80&w=800&auto=format&fit=crop",
            },
            {
              title: "Outdoor Tiling",
              description: "Durable finishes for a modern pool area.",
              href: "#",
              imageSrc: "https://images.unsplash.com/photo-1574359411659-15573a27fd0c?q=80&w=800&auto=format&fit=crop",
            },
            {
              title: "Emergency Electrical",
              description: "Rapid response troubleshooting for a local business.",
              href: "#",
              imageSrc: "https://images.unsplash.com/photo-1603796846097-bee99e4a601f?q=80&w=800&auto=format&fit=crop",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
