// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "projects" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ProjectsSection(): React.JSX.Element {
  return (
    <div id="projects" data-section="projects">
        <SectionErrorBoundary name="projects">
              <FeaturesRevealCardsBento
          tag="Recent Work"
          title="Portfolio Highlights"
          description="A glimpse into our recent craftsmanship and professional successes across Cape Town."
          items={[
            {
              title: "Electrical Refurb",
              description: "Panel board replacement and full certification.",
              href: "#",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3G8pr39VQA8qyoH5BQldYgFWqm6/uploaded-1783511764566-7o6o7qfu.jpg",
            },
            {
              title: "Interior Painting",
              description: "High-end finish for a modern luxury home.",
              href: "#",
              imageSrc: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&auto=format&fit=crop",
            },
            {
              title: "Kitchen Tiling",
              description: "Modern patterned tiles installed with precision.",
              href: "#",
              imageSrc: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?q=80&w=800&auto=format&fit=crop",
            },
            {
              title: "Garden Clearing",
              description: "Safe tree felling in a confined residential space.",
              href: "#",
              imageSrc: "https://images.unsplash.com/photo-1592424001806-53b00f324592?q=80&w=800&auto=format&fit=crop",
            },
            {
              title: "Ceiling Install",
              description: "Custom ceiling panels for a garage workshop.",
              href: "#",
              imageSrc: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=800&auto=format&fit=crop",
            },
            {
              title: "Outdoor Tiling",
              description: "Durable finishes for a modern pool area.",
              href: "#",
              imageSrc: "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?q=80&w=800&auto=format&fit=crop",
            },
            {
              title: "Emergency Electrical",
              description: "Rapid response troubleshooting for a local business.",
              href: "#",
              imageSrc: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?q=80&w=800&auto=format&fit=crop",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
