// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialColumnMarqueeCards from '@/components/sections/testimonial/TestimonialColumnMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialColumnMarqueeCards
          tag="Testimonials"
          title="Client Voices"
          description="See why Cape Town homeowners and property managers trust Team Work Projects."
          testimonials={[
            {
              name: "Sarah Johnson",
              role: "Homeowner",
              quote: "The electrical team responded so quickly when I had an urgent power failure. Exceptional service.",
              imageSrc: "http://img.b2bpic.net/free-photo/portrat-young-man-laughing_23-2148560405.jpg",
            },
            {
              name: "Mark Stevens",
              role: "Property Manager",
              quote: "They are now our go-to for all electrical and tiling maintenance across our portfolio.",
              imageSrc: "http://img.b2bpic.net/free-photo/he-is-satisfied-from-his-life_329181-2789.jpg",
            },
            {
              name: "Linda M.",
              role: "Homeowner",
              quote: "Beautiful tiling job in our kitchen. They were professional, clean, and quick.",
              imageSrc: "http://img.b2bpic.net/free-photo/happy-young-woman-sitting-sofa-home-portrait-comfortable-woman-winter-clothes-relaxing_657921-462.jpg",
            },
            {
              name: "David W.",
              role: "Real Estate Investor",
              quote: "Reliability is key for me, and Team Work Projects has never let me down.",
              imageSrc: "http://img.b2bpic.net/free-photo/smiling-woman-holding-big-flower-pot_23-2148396845.jpg",
            },
            {
              name: "Claire P.",
              role: "Small Business Owner",
              quote: "Professional, on time, and knowledgeable. Highly recommend their painting services.",
              imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-smiley-woman-construction_23-2149366626.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
